<a href="https://colab.research.google.com/github/19PA1A0470/AI-LAB/blob/master/adaboost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **ADA boost model**

In [0]:
# importimg required libraries
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix


In [0]:
# reading data
ipl=pd.read_csv("Iris.csv")
ipl

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [0]:
ipl.isna().any() # to find NA's

Id               False
SepalLengthCm    False
SepalWidthCm     False
PetalLengthCm    False
PetalWidthCm     False
Species          False
dtype: bool

In [0]:
#converting catorical feature to numerical feature
ipl['Species'].replace(to_replace=['Iris-setosa','Iris-versicolor','Iris-virginica'], value=[0,1,2],inplace=True)
ipl.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [0]:
# declaring featuresa and target variable
X = ipl[['SepalWidthCm','PetalLengthCm','PetalWidthCm','SepalLengthCm']].values
y= ipl['Species'].values
print('X=',X)
print('y=',y)

X= [[3.5 1.4 0.2 5.1]
 [3.  1.4 0.2 4.9]
 [3.2 1.3 0.2 4.7]
 [3.1 1.5 0.2 4.6]
 [3.6 1.4 0.2 5. ]
 [3.9 1.7 0.4 5.4]
 [3.4 1.4 0.3 4.6]
 [3.4 1.5 0.2 5. ]
 [2.9 1.4 0.2 4.4]
 [3.1 1.5 0.1 4.9]
 [3.7 1.5 0.2 5.4]
 [3.4 1.6 0.2 4.8]
 [3.  1.4 0.1 4.8]
 [3.  1.1 0.1 4.3]
 [4.  1.2 0.2 5.8]
 [4.4 1.5 0.4 5.7]
 [3.9 1.3 0.4 5.4]
 [3.5 1.4 0.3 5.1]
 [3.8 1.7 0.3 5.7]
 [3.8 1.5 0.3 5.1]
 [3.4 1.7 0.2 5.4]
 [3.7 1.5 0.4 5.1]
 [3.6 1.  0.2 4.6]
 [3.3 1.7 0.5 5.1]
 [3.4 1.9 0.2 4.8]
 [3.  1.6 0.2 5. ]
 [3.4 1.6 0.4 5. ]
 [3.5 1.5 0.2 5.2]
 [3.4 1.4 0.2 5.2]
 [3.2 1.6 0.2 4.7]
 [3.1 1.6 0.2 4.8]
 [3.4 1.5 0.4 5.4]
 [4.1 1.5 0.1 5.2]
 [4.2 1.4 0.2 5.5]
 [3.1 1.5 0.1 4.9]
 [3.2 1.2 0.2 5. ]
 [3.5 1.3 0.2 5.5]
 [3.1 1.5 0.1 4.9]
 [3.  1.3 0.2 4.4]
 [3.4 1.5 0.2 5.1]
 [3.5 1.3 0.3 5. ]
 [2.3 1.3 0.3 4.5]
 [3.2 1.3 0.2 4.4]
 [3.5 1.6 0.6 5. ]
 [3.8 1.9 0.4 5.1]
 [3.  1.4 0.3 4.8]
 [3.8 1.6 0.2 5.1]
 [3.2 1.4 0.2 4.6]
 [3.7 1.5 0.2 5.3]
 [3.3 1.4 0.2 5. ]
 [3.2 4.7 1.4 7. ]
 [3.2 4.5 1.5 6.4]
 [3.1 4.9

In [0]:
# splitting of data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, z, test_size=0.3,random_state=143)

NameError: ignored

In [0]:
print("X_train",X_train)
print("X_test",X_test)

print("y_train",y_train)
print("y_test",y_test)

In [0]:
#now building  adaboostclassifier on training sets and fitting 
classifier = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=1),
    n_estimators=100
)
classifier.fit(X_train, y_train)

In [0]:
#now predicting based on x_test values
predictions = classifier.predict(X_test)
predictions

In [0]:
y_test=y_test
predictions=predictions.reshape(-1,)


diff=pd.DataFrame({'Actual':y_test,'Predicted':predictions})
diff

In [0]:
#  classification  report of our model
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))




In [0]:
from sklearn.metrics import mean_squared_error#calculating error of our model
mean_squared_error(diff['Actual'],diff['Predicted'])


In [0]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, predictions))

# accuracy of classifier through ada boost method =**95%**

# **Decision tree model** 

In [0]:
#importing decision tree classifier
from sklearn.tree import DecisionTreeClassifier


In [0]:
#fittting the training set into model
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)


In [0]:

#testing the model
predict = dt.predict(X_test)
predict

In [0]:
#comparing actual with prediction
y_test=y_test
predict=predict.reshape(-1,)

diff=pd.DataFrame({'Actual':y_test,'Predicted':predict})
diff

In [0]:
#  classification  report of our model
from sklearn.metrics import classification_report
print(classification_report(y_test,predict))



In [0]:
#calculating error
from sklearn.metrics import mean_squared_error
mean_squared_error(diff['Actual'],diff['Predicted'])


In [0]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, predict))

# accuracy of classifier through Decision tree method =**93%**

# **Report**

**from the above we find the accuracy of the model is good by using ensemble method (ada boost)  then generalclassifier like  svm , decissiontree ,kNNclassifier etc**




